#!/bin/bash

alias be='bundle exec'
alias brightness='xrandr --output eDP1 --brightness'
alias java_ver='function _java_ver() {
	sudo update-java-alternatives -s java-$1-oracle;
};_java_ver'
alias wifi_restart='function _wifi_restart() {
	sudo service network-manager restart;
	exit;
};_wifi_restart'
alias task='gnome-system-monitor &'
alias search='function _search() {
	grep $1 -R ./
};_search'
alias mouse='function _mouse() {
	sudo rmmod psmouse;
	sudo insmod /lib/modules/4.1.6-040106-generic/kernel/drivers/input/mouse/psmouse.ko;
};_mouse'
