" For cool stuffs

set nocompatible	" Workaround for keyboard incompatibility (Set first)
set showcmd
set mouse=a			" Enable use of mouse

" Leader {{{
let mapleader = ","
" }}}

" Pathogen {{{
execute pathogen#infect()
" }}}

" Encoding {{{
scriptencoding utf-8
set encoding=utf-8
" }}}

" Colours {{{
syntax enable		" Enable syntax processing
set t_Co=256
" }}}

" Spaces and Tabs {{{
set tabstop=4			" Number of visual spaces per TAB
set softtabstop=4		" Number of spaces in tab when editing
set listchars:tab:»·,trail:·	" Configuration for tab and trailing
set list			" Show hidden chars
set autoindent			" Auto-indent
autocmd Filetype ocaml setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype c setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
" }}}

" UI Layout {{{
set number		" Set numberings at side
set cursorline		" Highlight current line
set showmatch		" Highlight matching [{()}]
" }}}

" Split Screen {{{
" window
nnoremap <silent> <A-Left>  :wincmd h<CR>
nnoremap <silent> <A-Right> :wincmd l<CR>
nnoremap <silent> <A-Up>    :wincmd k<CR>
nnoremap <silent> <A-Down>  :wincmd j<CR>
" buffer
nnoremap <leader>h   :leftabove  vnew<CR>
nnoremap <leader>l   :rightbelow vnew<CR>
nnoremap <leader>k   :leftabove  new<CR>
nnoremap <leader>j   :rightbelow new<CR>
"}}}

" Searching  {{{
set incsearch		" search as characters are entered
set hlsearch		" highlight matches
" Switch off highlighting of the current search results
nnoremap <CR> :nohlsearch<CR><CR>
" }}}

" Folding {{{

" }}}

" Airline settings {{{
set laststatus=2
set timeoutlen=50
let g:airline_theme = 'minimalist'
let g:airline_powerline_fonts = 1
" }}}

" Vimux settings {{{
map <leader>t yy<CR>
" }}}

