#!/bin/bash
#############################################
# install
# This script installs dotfiles found in
# the dotfile directory by creating symlinks
# from the home directory
#############################################

##############
# Variables
##############

DIR=$( dirname "${BASH_SOURCE[0]}" )	# Current directory
DOTDIR=$DIR/dotfiles					# Dotfiles directory
OLDDIR=~/dotfiles_old					# Old dotfiles backup directory
FILES=$(ls $DOTDIR)						# Get list of files in dotfile directory

##############

# Create old dotfiles directory in home directory
if [ ! -d "$OLDDIR" ]; then
	echo -n "Creating $OLDDIR for backup of any existing dotfiles in ~ ..."
	mkdir $OLDDIR
	echo "done"
	echo ""
fi

for file in $FILES; do
	# Move old files to old directory
	echo -n "Finding any existing dotfiles in home directory ..."
	if [ -f ~/.$file ]; then
		echo "Found"
		echo "Moving $file from ~ to $OLDDIR"
		mv ~/.$file $OLDDIR
	fi

	# Create new symlinks
	echo "Creating symlink to $file in home directory"
	ln -s $DOTDIR/$file ~/.$file

	echo ""
done
