#!/bin/bash

# Install some dependencies for Ruby
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties

# Get rbenv
git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_env
echo 'eval "$(rbenv init -)"' >> ~/.bash_env
. ~/.bashrc

# Get ruby-build in rbenv
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bash_env
. ~/.bashrc

# Install Ruby 2.1.2
rbenv install 2.1.2
rbenv global 2.1.2
ruby_ver=$(ruby -v)
echo 'Using Ruby version $ruby_ver'

# Do not install the documentation of each gem locally
echo "gem: --no-ri --no-rdoc" > ~/.gemrc

