#!/bin/bash
# Setting up Ubuntu
# The first parameter would be the user's username on git
# The second parameter is the user's email

username=$1
email=$2
cd ~

# Update
sudo apt-get update
echo 'Update successful'

# Get vim
sudo apt-get install vim

if [ ! -f ~/.vimrc ]
then
	touch ~/.vimrc	
fi

# Configure git
sudo apt-get install git-core
git config --global color.ui true
git config --global user.name $username
git config --global user.email $email

# Set user defined bin folder
mkdir ~/bin
echo 'export PATH="~/bin:$PATH"' >> ~/bin/.bash_env

# Key generation
if [ ! -d ~/.ssh ]
then
	ssh-keygen -t rsa -C $email
fi
echo 'Please paste the following at this link: https://github.com/settings/ssh'
cat ~/.ssh/id_rsa.pub
echo -e '\n'
echo 'Please run ssh -T git@github.com after you have done that'
echo 'You should get a message like this:'
echo 'Hi $username! You\'ve successfully authenticated, but GitHub does not provide shell access.'

echo '. ~/.bashrc'

sudo apt-get update
sudo apt install python3-dev python3-pip
sudo pip3 install thefuck

dconf load /org/gnome/terminal < ./config/org.gnome.terminal.conf
